config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :visitors, only: [:index, :show] do
    collection do
      get 'album'
    end
  end
  resources :users do
    resources :albums do
      resources :photos
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos
  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validate :validate_photos

  private
    def validate_photos
      errors.add(:photos, "count for this album if full") if photos.size > 25
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

  # Search data thorugh both the polymorphic association
  # Comment.ransack(commentable_of_Teacher_type_status_or_commentable_of_Student_type_status_in: ['active']).result
end

app/models/job.rb
class Delayed::Job < ApplicationRecord
  include Delayed::Backend::Base

  self.table_name = "delayed_jobs"

  attr_accessor :job_id

  before_validation :set_job_id

  before_create :check_details

  def akash
    puts "helloo"
  end
  
  def self.search(job_id)
    byebug
  end

  private

  def check_details
    byebug
  end

  def set_job_id
    data = YAML.load_dj(self.handler)
    byebug
    self.job_id = data.job_data['job_id']
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  belongs_to :album, optional: true

  validates :tagline, presence: true

  scope :with_preloaded_image, -> { preload(image_attachment: :blob) }
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums
  has_many :photos
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = @user.albums
  end

  def new
    @album = @user.albums.new
    @album.photos.build
  end

  def create
    @album = @user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to user_albums_path(@user), notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @photos = @album.photos
  end

  def edit
    @album.photos.build
  end

  def update
    respond_to do |format|
      if @album.update(album_params)

        job = MyJob.set(wait: 1.minutes).perform_later('dummy@example.com')
        jid = job.provider_job_id # getting provider_job_id here
        puts "----------------------------------------------------"
        puts "Provider job id ======provider_job_id=====>> #{jid}"
        puts "----------------------------------------------------"

        format.html { redirect_to user_albums_path(@user), notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to user_albums_path(@user), notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(
        :title,
        photos_attributes: [:tagline, :image, :user_id, :_destroy, :id]
      )
    end

    def set_user
      @user = current_user
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @photos = Photo.with_preloaded_image.last(25)
  end

  def album
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos.with_preloaded_image
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.haml
.container-fluid
  = form_for [@user, @album] do |f|
    - if @album.errors.any?
      #error_explanation
        %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
        %ul
          - @album.errors.full_messages.each do |message|
            %li= message

    .field
      = f.label :title
      = f.text_field :title

      %h3 Images
      = f.fields_for :photos do |image|
        = render 'photo_fields', f: image
      %br/
      .links
        = link_to_add_association 'Add image', f, :photos, class: 'btn btn-success'

    .actions
      = f.submit 'Save', class: 'btn btn-primary'

app/views/albums/_photo_fields.html.haml
.nested-fields
  = f.hidden_field :user_id, value: @user.id
  .field
    = f.label :image
    %br
    = f.file_field :image
  .field
    = f.label :tagline
    = f.text_field :tagline
  %br/
  = link_to_remove_association "Remove Image", f, class: 'btn btn-danger'

app/views/albums/edit.html.haml
.container-fluid
  %h1 Editing Album

  = render 'form'

  = link_to 'Show', user_album_path(@user, @album)
  \|
  = link_to 'Back', user_albums_path(@user)

app/views/albums/index.html.haml
.container-fluid
  %h2 My Albums
  %br
  = link_to 'New Album', new_user_album_path(@user), class: 'btn btn-primary'

  %table.table.table-hover
    %thead
      %tr
        %th Title
        %th Images
        %th Actions
    %tbody
      - @albums.each do |album|
        %tr
          %td
            = album.title
          %td
            = album.photos.count
          %td
            = link_to 'Show', user_album_path(@user, album), class: 'btn btn-info'
            = link_to 'Edit', edit_user_album_path(@user, album), class: 'btn btn-warning'
            = link_to 'Destroy', user_album_path(@user, album), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/albums/new.html.haml
.container-fluid
  %h1 New Album

  = render 'form'

  = link_to 'Back', user_albums_path(@user), class: 'btn btn-warning'

app/views/albums/show.html.haml
.container-fluid
  %h3
    = "Album : #{@album.title}"
  %h3
    = "Author : #{@album.user.email}"
  %br/
  - @photos.in_groups_of(3, false) do |row|
    .row
      - for photo in row
        - if photo.image.attached?
          .col-lg-4.col-md-4.col-xs-12.thumb
            %strong Tagline:
            %strong
              = photo.tagline
            %br/
            %a.thumbnail
              = image_tag photo.image.variant(resize: "400x300"), class: 'img-responsive'

  = link_to 'Edit', edit_user_album_path(@user, @album), class: 'btn btn-primary'
  \|
  = link_to 'Back', user_albums_path(@user), class: 'btn btn-warning'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Profile', user_albums_path(current_user)
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Albums', album_visitors_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Images Hub"
    %meta{content: "#{content_for?(:description) ? yield(:description) : "Images Hub"}", name: "description"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{role: "main"}
      = render 'layouts/messages'
      = yield

app/views/users/show.html.haml
%h3 User
%p
  Email: #{@user.email if @user.email}

app/views/visitors/album.html.haml
.container-fluid
  %h2 Albums

  %table.table.table-hover.table-responsive
    %thead
      %tr
        %th Title
        %th Author
        %th Images Count
        %th Actions
    %tbody
      - @albums.each do |album|
        %tr
          %td
            = album.title
          %td
            = album.user.email
          %td
            = album.photos.count
          %td
            = link_to 'Check Images', visitor_path(album), class: 'btn btn-info'

app/views/visitors/index.html.haml
.container-fluid
  %h3 Welcome To Images Hub
  %br/
  - @photos.in_groups_of(3, false) do |row|
    .row
      - for photo in row
        - if photo.image.attached?
          .col-lg-4.col-md-4.col-xs-12.thumb
            %a.thumbnail.img-container
              = image_tag photo.image.variant(resize: "400x300"), class: 'image img-responsive'
              .middle
                .text
                  = photo.user.email

app/views/visitors/show.html.haml
.container-fluid
  %h3
    = "Album : #{@album.title}"
  %h3
    = "Author : #{@album.user.email}"
  %br/
  - @photos.in_groups_of(3, false) do |row|
    .row
      - for photo in row
        - if photo.image.attached?
          .col-lg-4.col-md-4.col-xs-12.thumb
            %strong Tagline:
            %strong
              = photo.tagline
            %br/
            %a.thumbnail
              = image_tag photo.image.variant(resize: "400x300"), class: 'img-responsive'

  = link_to 'Back', album_visitors_path, class: 'btn btn-warning'